
all: TicTacToeClient.java TicTacToeServer.java
	javac TicTacToeClient.java TicTacToeServer.java

TicTacToeClient: TicTacToeClient.java
	javac TicTacToeClient.java
TicTacToeServer: TicTacToeServer.java
	javac TicTacToeServer.java
clean:
	rm *.class
